[ClassVersion("1.0.0"), FriendlyName("WaitForEventStore")]
class WaitForEventStore : OMI_BaseResource
{
    [Key, Description("Specifies EventStore URL")] string Url;

    [write, Description("Repeats")] string Repeats;
    [write, Description("SecondsToWait")] string SecondsToWait;
};
